###
GET http://localhost:9000/api/cliente HTTP/1.1
###
GET http://localhost:9000/api/cliente/pru@3 HTTP/1.1

###
POST http://localhost:9000/api/cliente HTTP/1.1
Content-Type: application/json

{
    "correo":"pru@5",
    "nombre": "prueba1",
    "apellidos": "apellido_prueb1",
    "telefono": 5547130095
}

###
DELETE http://localhost:9000/api/cliente/pru@5 HTTP/1.1

###
PUT http://localhost:9000/api/cliente/pru@4 HTTP/1.1
Content-Type: application/json

{
    "correo":"pru@5",
    "nombre": "prueba1",
    "apellidos": "apellido_prueb1",
    "telefono": 5547130095
}